.PHONY: clean All

All:
	@echo "----------Building project:[ 02_helloworld_with_args - Debug ]----------"
	@cd "02_helloworld_with_args" && "$(MAKE)" -f  "02_helloworld_with_args.mk"
clean:
	@echo "----------Cleaning project:[ 02_helloworld_with_args - Debug ]----------"
	@cd "02_helloworld_with_args" && "$(MAKE)" -f  "02_helloworld_with_args.mk" clean
