---
title: "Gapminder: exploratory analysis"
output: html_notebook
---

This is just for studies purposes. 

```{r}
library("tidyverse")
library("ggplot2")
dataset <- read.csv("data/gapminder.tsv", sep="\t")
str(dataset)
```

Let's plot it!

```{r}
ggplot(dataset, aes(x=gdpPercap, y=lifeExp, 
                    size=pop, color=continent)) +
  geom_point() +
  scale_x_log10() +
  facet_wrap(~year)
```

Let's filter for countries in Americas.

```{r}
america <- dataset %>%
  filter(continent == "Americas")

america
```

Now let's plot the total GDP per year and country and the population.

```{r}
america_ttlGPD <- america %>%
  mutate(GDP = gdpPercap * pop)
ggplot(america_ttlGPD, aes(x=GDP, y=pop, color=year)) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10() +
  facet_wrap(~country)
```

Ok, let's work with BRICS (Brazil, Russia, India, China and South Africa)

```{r}
southam <- dataset %>%
  filter(country == "Argentina" | country == "Bolivia" | country == "Brazil" | country == "Chile" |
           country == "Colombia" | country == "Ecuador" | country == "Paraguay" | country == "Peru" |
           country == "Uruguay" | country == "Venezuela")

ggplot(southam, aes(x = gdpPercap/1000, y = lifeExp, color = factor(year), size = pop)) +
  geom_point() +
  facet_wrap(~country)
```

